### ISSUE TITLE
rafcon library config relative path undefined behaviour

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#223]
I had a rafcon library config:

``` yaml
LIBRARY_PATHS:
    rmpl: rmpl
    test: test_rmpl
    links_and_nodes: links_and_nodes
TYPE: SM_CONFIG
```

When I loaded this config with rafcon started from the links and nodes manager the paths were resolved to /tmp/~relative_path~ and not relative to the config file path.
Changing the definition with ./ notation helped to resolve the issue:

``` yaml
LIBRARY_PATHS:
    rmpl: ./rmpl
    test: ./test_rmpl
    links_and_nodes: ./links_and_nodes
TYPE: SM_CONFIG
```

Originally created by @peter-lehner  at 2016-11-11 14:54:04+00:00 (moved from RMC internal repository)
